#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid tainrs python3 -OO "${APP_DIR}/bin/SABnzbd.py" --config-file "${CONFIG_DIR}" --server 0.0.0.0:8080 --browser 0
